// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'E:/keepcharts/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from 'E:/keepcharts/node_modules/dumi/theme-default/slots/SearchBar/index.js';
