// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/yangbo/develop/keepcharts/node_modules/dumi/theme-default/layouts/DocLayout/index.js';
